const words=['digital','web','software','business','automation'];const word=document.getElementById('rotating-word');let i=0;if(word){setInterval(()=>{i=(i+1)%words.length;word.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-12px)'}],{duration:220,easing:'ease-in'}).finished.then(()=>{word.textContent=words[i];word.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:380,easing:'ease-out'});});},2200)}const particles=document.querySelector('.particles');if(particles){for(let n=0;n<34;n++){const p=document.createElement('i');p.className='particle';p.style.left=Math.random()*100+'%';p.style.animationDuration=(7+Math.random()*12)+'s';p.style.animationDelay=(-Math.random()*14)+'s';p.style.transform=`scale(${.5+Math.random()*1.5})`;particles.appendChild(p)}}const glow=document.querySelector('.cursor-glow');if(glow)document.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();

/* Repair and normalize the project showcase cards. This also protects the layout if an older/malformed HTML version is cached. */
const projectList=document.querySelector('.project-list');if(projectList){const projects=[
['01','platform','LIVE PRODUCT','Tools Hub App','A growing platform of practical online utilities for developers, creators, businesses and everyday users.',['Online Tools','Web Platform','Product'],'https://toolshubapp.com/','↗'],
['02','wordpress','WORDPRESS WEBSITE','Prime Hot Deal','A WordPress-based web project added to the portfolio as part of our website development experience.',['WordPress','Web Development','CMS'],'https://primehotdeal.com/','↗'],
['03','wordpress','WORDPRESS / AFFILIATE','Prime Hot Deal Affiliate','An affiliate-focused WordPress project demonstrating content, product and affiliate website development.',['WordPress','Affiliate','Content'],'https://affiliate.primehotdeal.com/','↗'],
['04','platform','WEB PLATFORM','Prime Hot Deal Lucky Draw','A dedicated web platform project presented as part of our growing portfolio of custom web experiences.',['Web Platform','Custom UI','PHP / JS'],'https://luckydraw.primehotdeal.com/','↗'],
['05','software','BUSINESS SOFTWARE','POS & Inventory Solutions','Retail-focused software concepts covering sales, products, stock, customers, suppliers and reporting.',['POS','Inventory','Reports'],null,'→'],
['06','extensions','BROWSER TOOLS','Chrome Extension Solutions','Productivity and developer-focused browser extensions designed to simplify repetitive web tasks.',['Chrome','Automation','Productivity'],null,'→']
];projectList.innerHTML=projects.map(([num,cat,label,title,desc,tags,url,arrow])=>{const content=`<div class="project-number">${num}</div><div><small>${label}</small><h3>${title}</h3><p>${desc}</p><div class="tags">${tags.map(t=>`<span>${t}</span>`).join('')}</div></div><span class="arrow">${arrow}</span>`;return url?`<a class="project ${num==='01'?'featured ':''}project-card" data-category="${cat}" href="${url}" target="_blank" rel="noreferrer">${content}</a>`:`<div class="project project-card" data-category="${cat}">${content}</div>`}).join('')}

document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>{card.style.display=filter==='all'||card.dataset.category===filter?'grid':'none'})}));

/* Load the mobile-only project card fixes without requiring another HTML deployment edit. */
const mobileFix=document.createElement('link');mobileFix.rel='stylesheet';mobileFix.href='mobile-fix.css';document.head.appendChild(mobileFix);
